name: GitHub Actions Demo

run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Yarn install
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: yarn install
  build:
    runs-on: ubuntu-latest
    needs: setup
    uses: actions/checkout@v4
    steps:
      - run: yarn build
  linter:
    runs-on: ubuntu-latest
    needs: build
    uses: actions/checkout@v4
    steps:
      - run: yarn lint
